# Generated by Django 6.0.1 on 2026-01-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0003_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
